modLoader="javafml"
loaderVersion="[28.1]"
[[mods]]
modId="bedrocktools2"
version="1.1.0"
displayName="Bedrock Tools 2"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-tools-2"
authors="Tanttinator"
description='''
Create tools and armor from bedrock! Because I know you always wanted to"'''
updateJSONURL="https://tanttinator.github.io/BedrockTools2/update_checker.json"